stages:
  - sync

variables:
  PUNCH_GITHUB_USER: ${PUNCH_GITHUB_USER}
  PUNCH_GITHUB_TOKEN: ${PUNCH_GITHUB_TOKEN}

Sync with Github:
  image: alpine:3.15
  stage: sync
  retry: 1
  tags:
    - docker-runner
  before_script:
    - apk update
    - apk add git
  script:
    - git remote remove github || true
    - git remote add github https://${PUNCH_GITHUB_USER}:${PUNCH_GITHUB_TOKEN}@github.com/punchplatform/punch-parser-archetype.git
    - git push github HEAD:8.0
  rules:
    - if: '$CI_COMMIT_BRANCH == "8.0-github"'
