stages:
  #- test # puncher image required to test before
   - release

release:
  image: maven:3.6.3-openjdk-11
  stage: release
  when: manual
  tags:
    - ea_kube
  before_script:
    # Install JFrog CLI
    - curl -fL https://getcli.jfrog.io | sh
    # Configure Artifactory instance with JFrog CLI
    # Environment variables are defined in Settings > CICD > Variables
    - ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS --interactive=false
    - ./jfrog config show
    # Configure Maven plugin with JFrog CLI
    - ./jfrog rt mvnc --server-id-deploy=Default-Server --repo-deploy-releases=private-mvn-punch --repo-deploy-snapshots=private-mvn-punch
    # Configure .m2 for build
    - export M2_HOME=/usr/share/maven
  script:
    # Run the MVN command
    - ./jfrog rt mvn clean install --build-name=punch-parser-artefact --build-number=$CI_JOB_ID
    # Collect the environment variables
    #- ./jfrog rt bce common-punchlets $CI_JOB_ID
    # Pass the build information to Artifactory
    #- ./jfrog rt bp common-punchlets $CI_JOB_ID
