---
apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: sample
  namespace: sample
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '7770'
spec:
  dependencies:
    - punch-parsers:${groupId}:${artifactId}:${version}
  dag:
  - id: input
    kind: source
    type: generator_source
    exit_conditions:
     success:
        acks_greater_or_equal_to: 1
        require_no_remaining_row_to_inject: true
        require_no_pending_row: true
     failure:
        fails_greater_or_equal_to: 1
    settings:
      expectation: none
      acked:
      messages:
        - "your sample log"
    out:
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
  - id: parser
    kind: function
    type: punchlet_function
    settings:
      resources:
      - name: color_codes
        url: sample/resources/color_codes.json
        type: file
        format: json
      - name: standard_groks
        url: /usr/share/punch/resources/patterns
        type: file
        format: grok
      punchlets:
      - sample/parser.punch
      - sample/enrich.punch
